import { Page, expect } from '@playwright/test';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const SCREENSHOT_DIR = join(HERE, '..', 'screenshots');

/** Five fixture images generated by global-setup.ts, in alphabetical order. */
export const IMAGE_FILES = [
  '01-alpha.png',
  '02-bravo.png',
  '03-charlie.png',
  '04-delta.png',
  '05-echo.png',
];

/**
 * Open a gallery folder and wait for the React square grid to render.
 * Returns once every fixture image item is attached to the DOM.
 */
export async function openGallery(page: Page, folder: string) {
  await page.goto(`/g/${folder}`);
  // React clears `.gallery-images` and mounts the square grid into it.
  const grid = page.locator('.image-grid.square-grid');
  await expect(grid).toBeVisible();
  await expect(grid.locator('.image-item')).toHaveCount(IMAGE_FILES.length);
  // Let thumbnail background-images resolve so screenshots show real pixels.
  await page.waitForLoadState('networkidle');
}

/**
 * The rendered image order, as filenames. In square-grid mode the DOM order of
 * `.image-item` is the server's sort order (masonry would scramble it across
 * columns), so the basename of each `data-id` is the on-screen order.
 */
export async function renderedOrder(page: Page): Promise<string[]> {
  const ids = await page.locator('.image-grid.square-grid .image-item').evaluateAll(
    (items) => items.map((el) => el.getAttribute('data-id') || ''),
  );
  return ids.map((id) => id.split('/').pop() || '');
}

export async function shot(page: Page, name: string) {
  await page.screenshot({ path: join(SCREENSHOT_DIR, `${name}.png`), fullPage: true });
}
