if(DEFINED ENV{AOM_SOURCE_DIR} AND EXISTS "$ENV{AOM_SOURCE_DIR}/CMakeLists.txt")
  set(FETCHCONTENT_SOURCE_DIR_AOM "$ENV{AOM_SOURCE_DIR}" CACHE PATH "Cached AOM source tree" FORCE)
  set(FETCHCONTENT_SOURCE_DIR_LIBAOM "$ENV{AOM_SOURCE_DIR}" CACHE PATH "Cached AOM source tree" FORCE)
endif()
